export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'zh', name: 'Mandarin', native: '中文' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
];

export const KIOSK_STRINGS = {
  en: {
    title: 'Emergency Check-In',
    subtitle: 'Scan vitals. Speak symptoms in your language.',
    selectLang: 'Select Language',
    whoTitle: 'Who is this check-in for?',
    me: 'Me (Adult)',
    meDesc: 'Self check-in',
    child: 'Child',
    childDesc: 'Under 12 years',
    someoneElse: 'Someone I\'m with',
    someoneElseDesc: 'Family member or friend',
    howOld: 'How old is your child?',
    paediatricNote: 'Paediatric Note: Camera scan is skipped for children under 12. A nurse will manually check vitals.',
    aboutYouTitle: 'About you',
    stepOf: 'Step {n} of {total}',
    ageLabel: 'How old are you?',
    sexLabel: 'Sex assigned at birth (for medical care)',
    female: 'Female',
    male: 'Male',
    intersex: 'Intersex',
    preferNot: 'Prefer not to say',
    pronounsTitle: 'Pronouns (optional)',
    nameTitle: 'Your Name',
    nameSubtitle: 'First and last name',
    emergencyNotice: 'Chest pain or can\'t breathe? Arrived by ambulance? Go straight to the desk.',
    back: 'Back',
    continue: 'Continue',
    skip: 'Skip',
    askStaff: 'Ask staff',
    interpreterOff: 'I need a sign language interpreter',
    interpreterOn: '✓ Sign language interpreter requested',
    alreadyCheckedIn: 'Already checked in and feeling worse?',
    years: 'years',
    months: 'months',
    whyWeAsk: 'Why we ask: sex assigned at birth helps with organ-specific risks and lab reference ranges.',
    skipPronouns: 'Skip pronouns',
    pronouns: {
      'he/him': 'he/him',
      'she/her': 'she/her',
      'they/them': 'they/them',
      other: 'other',
    },
    recheckKicker: 'Re-check symptoms',
    recheckTitle: 'Already checked in?',
    recheckBody: 'Enter the ticket number from your check-in (for example A-17) to rescan your vitals and report new symptoms.',
    rescan: 'Rescan symptoms',
    measuring: 'Measuring vitals...',
    lookAtCamera: 'Please look at the camera and breathe normally.',
    noVideo: 'No video is recorded. Only pulse and breathing are measured.',
    yourPulse: 'Your pulse',
    breathing: 'Breathing',
    breathsPerMin: 'breaths/min',
    describeTitle: 'Describe your symptoms',
    describeSub: 'Press the button below and speak naturally in your language.',
    tapToSpeak: 'Tap the microphone to speak',
    listening: 'Listening... speak now (tap to stop)',
    whatYouSaid: 'What you said',
    typeInstead: 'Type instead',
    hideTextBox: 'Hide text box',
    listeningPlaceholder: 'Listening to your voice...',
    spokenPlaceholder: 'Your spoken words will appear here...',
    typeSymptoms: 'Type your symptoms here...',
    painQuestion: 'How bad is the pain?',
    noPain: '0 - No pain',
    worstPain: '10 - Worst pain',
    next: 'Next',
    backToSymptoms: 'Back to symptoms',
    oneMoreQuestion: 'One more question',
    preparingQuestion: 'Preparing a question for you...',
    hearAgain: 'Hear it again',
    listenToQuestion: 'Listen to the question...',
    tapToAnswer: 'Tap the microphone to answer',
    yourAnswer: 'Your answer',
    answerPlaceholder: 'Your answer will appear here...',
    typeAnswer: 'Type your answer here...',
    quickTitle: 'A few quick questions',
    quickSub: 'This helps us prioritize your care. You can skip any question.',
    allergyQ: 'Are you allergic to any medicines?',
    whichOne: 'Which one?',
    allergyExample: 'e.g. penicillin',
    medsQ: 'Do you take any medicines?',
    medsExample: 'e.g. aspirin, insulin',
    onsetQ: 'When did this start?',
    detected: 'From what you said:',
    onset: {
      'Just now': 'Just now',
      Today: 'Today',
      'A few days': 'A few days ago',
      'A week or more': 'A week or more',
    },
    pregnantQ: 'Could you be pregnant?',
    yes: 'Yes',
    no: 'No',
    notSure: 'Not sure',
    analyzing: 'Checking you in...',
    checkIn: 'Check in',
    checkedIn: 'You\'re checked in',
    inQueue: 'You\'re in the queue. The sickest patients are seen first, so your wait may change.',
    yourTicket: 'Your ticket number',
    boardNote: 'Watch the waiting room screen for your number.',
    scanQr: 'Scan to follow your place on your phone',
    summary: 'Your check-in',
    symptomsLabel: 'Symptoms',
    vitalsLabel: 'Vitals',
    nurseVitals: 'A nurse will take your vitals',
    pulse: 'Pulse',
    feelWorse: 'If you feel much worse, tell staff right away.',
    done: 'Done',
    tapDone: 'Tap Done when you\'ve scanned the code so the next person can check in.',
    staffNotified: 'Staff have been notified. Someone is coming to help you.',
    dismiss: 'Dismiss',
    intakeError: 'Something went wrong. Please go to the triage desk.',
    networkError: 'Connection problem. Please go to the triage desk.',
  },
  fr: {
    title: 'Inscription aux Urgences',
    subtitle: 'Scannez vos constantes. Décrivez vos symptômes dans votre langue.',
    selectLang: 'Choisissez votre langue',
    whoTitle: 'Pour qui est cette inscription ?',
    me: 'Moi (Adulte)',
    meDesc: 'Auto-inscription',
    child: 'Enfant',
    childDesc: 'Moins de 12 ans',
    someoneElse: 'Un proche',
    someoneElseDesc: 'Membre de la famille ou ami',
    howOld: 'Quel âge a votre enfant ?',
    paediatricNote: 'Note pédiatrique : L\'analyse caméra est ignorée pour les enfants de moins de 12 ans.',
    aboutYouTitle: 'À propos de vous',
    stepOf: 'Étape {n} sur {total}',
    ageLabel: 'Quel âge avez-vous ?',
    sexLabel: 'Sexe assigné à la naissance (pour soins médicaux)',
    female: 'Femme',
    male: 'Homme',
    intersex: 'Intersexe',
    preferNot: 'Ne préfère pas répondre',
    pronounsTitle: 'Pronom (optionnel)',
    nameTitle: 'Votre nom',
    nameSubtitle: 'Prénom et initiale du nom',
    emergencyNotice: 'Douleur thoracique ou difficulté à respirer ? Arrivé en ambulance ? Allez directement au bureau.',
    back: 'Retour',
    continue: 'Continuer',
    skip: 'Passer',
    askStaff: 'Demander au personnel',
    interpreterOff: 'J\'ai besoin d\'un interprète en langue des signes',
    interpreterOn: '✓ Interprète en langue des signes demandé',
    alreadyCheckedIn: 'Déjà enregistré et vous vous sentez plus mal ?',
    years: 'ans',
    months: 'mois',
    whyWeAsk: 'Pourquoi : le sexe à la naissance aide à évaluer certains risques et les valeurs de laboratoire.',
    skipPronouns: 'Passer',
    pronouns: {
      'he/him': 'il',
      'she/her': 'elle',
      'they/them': 'iel',
      other: 'autre',
    },
    recheckKicker: 'Nouvelle vérification',
    recheckTitle: 'Déjà enregistré ?',
    recheckBody: 'Entrez votre numéro de ticket (par exemple A-17) pour refaire la mesure et signaler de nouveaux symptômes.',
    rescan: 'Refaire la vérification',
    measuring: 'Mesure des signes vitaux...',
    lookAtCamera: 'Regardez la caméra et respirez normalement.',
    noVideo: 'Aucune vidéo n\'est enregistrée. Seuls le pouls et la respiration sont mesurés.',
    yourPulse: 'Votre pouls',
    breathing: 'Respiration',
    breathsPerMin: 'resp./min',
    describeTitle: 'Décrivez vos symptômes',
    describeSub: 'Appuyez sur le bouton et parlez naturellement dans votre langue.',
    tapToSpeak: 'Appuyez sur le micro pour parler',
    listening: 'Écoute en cours... parlez (appuyez pour arrêter)',
    whatYouSaid: 'Ce que vous avez dit',
    typeInstead: 'Écrire plutôt',
    hideTextBox: 'Masquer la zone de texte',
    listeningPlaceholder: 'Écoute de votre voix...',
    spokenPlaceholder: 'Vos paroles apparaîtront ici...',
    typeSymptoms: 'Écrivez vos symptômes ici...',
    painQuestion: 'Quelle est l\'intensité de la douleur ?',
    noPain: '0 - Aucune douleur',
    worstPain: '10 - Douleur maximale',
    next: 'Suivant',
    backToSymptoms: 'Retour aux symptômes',
    oneMoreQuestion: 'Encore une question',
    preparingQuestion: 'Préparation de votre question...',
    hearAgain: 'Réécouter',
    listenToQuestion: 'Écoutez la question...',
    tapToAnswer: 'Appuyez sur le micro pour répondre',
    yourAnswer: 'Votre réponse',
    answerPlaceholder: 'Votre réponse apparaîtra ici...',
    typeAnswer: 'Écrivez votre réponse ici...',
    quickTitle: 'Quelques questions rapides',
    quickSub: 'Cela nous aide à prioriser vos soins. Vous pouvez passer une question.',
    allergyQ: 'Êtes-vous allergique à des médicaments ?',
    whichOne: 'Lequel ?',
    allergyExample: 'ex. pénicilline',
    medsQ: 'Prenez-vous des médicaments ?',
    medsExample: 'ex. aspirine, insuline',
    onsetQ: 'Quand cela a-t-il commencé ?',
    detected: 'D\'après ce que vous avez dit :',
    onset: {
      'Just now': 'À l\'instant',
      Today: 'Aujourd\'hui',
      'A few days': 'Il y a quelques jours',
      'A week or more': 'Une semaine ou plus',
    },
    pregnantQ: 'Pourriez-vous être enceinte ?',
    yes: 'Oui',
    no: 'Non',
    notSure: 'Je ne sais pas',
    analyzing: 'Enregistrement en cours...',
    checkIn: 'M\'enregistrer',
    checkedIn: 'Vous êtes enregistré',
    inQueue: 'Vous êtes dans la file. Les patients les plus malades sont vus en premier, votre attente peut donc changer.',
    yourTicket: 'Votre numéro de ticket',
    boardNote: 'Surveillez l\'écran de la salle d\'attente pour votre numéro.',
    scanQr: 'Scannez pour suivre votre place sur votre téléphone',
    summary: 'Votre enregistrement',
    symptomsLabel: 'Symptômes',
    vitalsLabel: 'Signes vitaux',
    nurseVitals: 'Une infirmière prendra vos signes vitaux',
    pulse: 'Pouls',
    feelWorse: 'Si vous vous sentez beaucoup plus mal, prévenez le personnel immédiatement.',
    done: 'Terminé',
    tapDone: 'Appuyez sur Terminé après avoir scanné le code pour libérer la borne.',
    staffNotified: 'Le personnel a été prévenu. Quelqu\'un arrive pour vous aider.',
    dismiss: 'Fermer',
    intakeError: 'Un problème est survenu. Veuillez vous rendre à l\'accueil.',
    networkError: 'Problème de connexion. Veuillez vous rendre à l\'accueil.',
  },
  es: {
    title: 'Registro de Emergencias',
    subtitle: 'Escanee sus signos vitales. Describa sus síntomas en su idioma.',
    selectLang: 'Seleccione su idioma',
    whoTitle: '¿Para quién es este registro?',
    me: 'Yo (Adulto)',
    meDesc: 'Registro personal',
    child: 'Niño/a',
    childDesc: 'Menor de 12 años',
    someoneElse: 'Alguien que me acompaña',
    someoneElseDesc: 'Familiar o amigo',
    howOld: '¿Cuántos años tiene su hijo/a?',
    paediatricNote: 'Nota pediátrica: Se omite el escaneo por cámara para menores de 12 años.',
    aboutYouTitle: 'Acerca de usted',
    stepOf: 'Paso {n} de {total}',
    ageLabel: '¿Cuántos años tiene?',
    sexLabel: 'Sexo asignado al nacer (para atención médica)',
    female: 'Mujer',
    male: 'Hombre',
    intersex: 'Intersexual',
    preferNot: 'Prefiero no decir',
    pronounsTitle: 'Pronombres (opcional)',
    nameTitle: 'Su nombre',
    nameSubtitle: 'Nombre e inicial del apellido',
    emergencyNotice: '¿Dolor de pecho o dificultad para respirar? ¿Llegó en ambulancia? Vaya directamente al mostrador.',
    back: 'Volver',
    continue: 'Continuar',
    skip: 'Omitir',
    askStaff: 'Pedir ayuda al personal',
    interpreterOff: 'Necesito un intérprete de lengua de señas',
    interpreterOn: '✓ Intérprete de lengua de señas solicitado',
    alreadyCheckedIn: '¿Ya se registró y se siente peor?',
    years: 'años',
    months: 'meses',
    whyWeAsk: 'Por qué preguntamos: el sexo al nacer ayuda a evaluar ciertos riesgos y valores de laboratorio.',
    skipPronouns: 'Omitir',
    pronouns: {
      'he/him': 'él',
      'she/her': 'ella',
      'they/them': 'elle',
      other: 'otro',
    },
    recheckKicker: 'Nueva revisión',
    recheckTitle: '¿Ya se registró?',
    recheckBody: 'Ingrese su número (por ejemplo A-17) para volver a medir sus signos vitales e informar nuevos síntomas.',
    rescan: 'Volver a revisar',
    measuring: 'Midiendo signos vitales...',
    lookAtCamera: 'Mire a la cámara y respire con normalidad.',
    noVideo: 'No se graba video. Solo se miden el pulso y la respiración.',
    yourPulse: 'Su pulso',
    breathing: 'Respiración',
    breathsPerMin: 'resp./min',
    describeTitle: 'Describa sus síntomas',
    describeSub: 'Presione el botón y hable con naturalidad en su idioma.',
    tapToSpeak: 'Toque el micrófono para hablar',
    listening: 'Escuchando... hable ahora (toque para parar)',
    whatYouSaid: 'Lo que dijo',
    typeInstead: 'Escribir',
    hideTextBox: 'Ocultar cuadro de texto',
    listeningPlaceholder: 'Escuchando su voz...',
    spokenPlaceholder: 'Sus palabras aparecerán aquí...',
    typeSymptoms: 'Escriba sus síntomas aquí...',
    painQuestion: '¿Qué tan fuerte es el dolor?',
    noPain: '0 - Sin dolor',
    worstPain: '10 - Dolor máximo',
    next: 'Siguiente',
    backToSymptoms: 'Volver a los síntomas',
    oneMoreQuestion: 'Una pregunta más',
    preparingQuestion: 'Preparando una pregunta para usted...',
    hearAgain: 'Escuchar otra vez',
    listenToQuestion: 'Escuche la pregunta...',
    tapToAnswer: 'Toque el micrófono para responder',
    yourAnswer: 'Su respuesta',
    answerPlaceholder: 'Su respuesta aparecerá aquí...',
    typeAnswer: 'Escriba su respuesta aquí...',
    quickTitle: 'Unas preguntas rápidas',
    quickSub: 'Esto nos ayuda a priorizar su atención. Puede omitir cualquier pregunta.',
    allergyQ: '¿Es alérgico a algún medicamento?',
    whichOne: '¿Cuál?',
    allergyExample: 'ej. penicilina',
    medsQ: '¿Toma algún medicamento?',
    medsExample: 'ej. aspirina, insulina',
    onsetQ: '¿Cuándo empezó?',
    detected: 'Según lo que dijo:',
    onset: {
      'Just now': 'Hace un momento',
      Today: 'Hoy',
      'A few days': 'Hace unos días',
      'A week or more': 'Una semana o más',
    },
    pregnantQ: '¿Podría estar embarazada?',
    yes: 'Sí',
    no: 'No',
    notSure: 'No estoy seguro',
    analyzing: 'Registrándolo...',
    checkIn: 'Registrarme',
    checkedIn: 'Está registrado',
    inQueue: 'Está en la fila. Los pacientes más graves se atienden primero, así que su espera puede cambiar.',
    yourTicket: 'Su número',
    boardNote: 'Mire la pantalla de la sala de espera para ver su número.',
    scanQr: 'Escanee para seguir su lugar en su teléfono',
    summary: 'Su registro',
    symptomsLabel: 'Síntomas',
    vitalsLabel: 'Signos vitales',
    nurseVitals: 'Una enfermera tomará sus signos vitales',
    pulse: 'Pulso',
    feelWorse: 'Si se siente mucho peor, avise al personal de inmediato.',
    done: 'Listo',
    tapDone: 'Toque Listo cuando haya escaneado el código para que la siguiente persona pueda registrarse.',
    staffNotified: 'Se avisó al personal. Alguien viene a ayudarle.',
    dismiss: 'Cerrar',
    intakeError: 'Algo salió mal. Por favor, acuda al mostrador de triaje.',
    networkError: 'Problema de conexión. Por favor, acuda al mostrador de triaje.',
  },
  ar: {
    title: 'تسجيل الدخول للطوارئ',
    subtitle: 'افحص مؤشراتك الحيوية. صف أعراضك بلغتك.',
    selectLang: 'اختر اللغة / Select Language',
    whoTitle: 'لمن هذا التسجيل؟',
    me: 'أنا (شخص بالغ)',
    meDesc: 'تسجيل ذاتي',
    child: 'طفل',
    childDesc: 'أقل من ١٢ سنة',
    someoneElse: 'شخص معي',
    someoneElseDesc: 'فرد من العائلة أو صديق',
    howOld: 'كم عمر طفلك؟',
    paediatricNote: 'ملاحظة للأطفال: يتم تخطي الفحص بالكاميرا للأطفال دون سن ١٢ عاماً.',
    aboutYouTitle: 'معلومات عنك',
    stepOf: 'الخطوة {n} من {total}',
    ageLabel: 'كم عمرك؟',
    sexLabel: 'الجنس المحدد عند الولادة',
    female: 'أنثى',
    male: 'ذكر',
    intersex: 'ثنائي الجنس',
    preferNot: 'أفضل عدم الإجابة',
    pronounsTitle: 'الضمائر (اختياري)',
    nameTitle: 'اسمك',
    nameSubtitle: 'الاسم الأول والحرف الأول من الكنية',
    emergencyNotice: 'ألم بالصدر أو صعوبة في التنفس؟ وصلتم بسيارة إسعاف؟ توجهوا فوراً للمكتب.',
    back: 'رجوع',
    continue: 'متابعة',
    skip: 'تخطي',
    askStaff: 'اسأل الموظفين',
    interpreterOff: 'أحتاج إلى مترجم لغة إشارة',
    interpreterOn: '✓ تم طلب مترجم لغة الإشارة',
    alreadyCheckedIn: 'مسجل بالفعل وتشعر بسوء أكثر؟',
    years: 'سنوات',
    months: 'أشهر',
    whyWeAsk: 'لماذا نسأل: الجنس عند الولادة يساعد في تقييم بعض المخاطر وقيم التحاليل.',
    skipPronouns: 'تخطي',
    pronouns: {
      'he/him': 'هو',
      'she/her': 'هي',
      'they/them': 'محايد',
      other: 'آخر',
    },
    recheckKicker: 'إعادة الفحص',
    recheckTitle: 'مسجل بالفعل؟',
    recheckBody: 'أدخل رقم تذكرتك (مثلاً A-17) لإعادة قياس مؤشراتك الحيوية والإبلاغ عن أعراض جديدة.',
    rescan: 'إعادة الفحص',
    measuring: 'جارٍ قياس المؤشرات الحيوية...',
    lookAtCamera: 'انظر إلى الكاميرا وتنفس بشكل طبيعي.',
    noVideo: 'لا يتم تسجيل أي فيديو. يتم قياس النبض والتنفس فقط.',
    yourPulse: 'نبضك',
    breathing: 'التنفس',
    breathsPerMin: 'نفس/دقيقة',
    describeTitle: 'صف أعراضك',
    describeSub: 'اضغط على الزر أدناه وتحدث بشكل طبيعي بلغتك.',
    tapToSpeak: 'اضغط على الميكروفون للتحدث',
    listening: 'جارٍ الاستماع... تحدث الآن (اضغط للإيقاف)',
    whatYouSaid: 'ما قلته',
    typeInstead: 'الكتابة بدلاً من ذلك',
    hideTextBox: 'إخفاء مربع النص',
    listeningPlaceholder: 'جارٍ الاستماع إلى صوتك...',
    spokenPlaceholder: 'ستظهر كلماتك هنا...',
    typeSymptoms: 'اكتب أعراضك هنا...',
    painQuestion: 'ما مدى شدة الألم؟',
    noPain: '0 - لا ألم',
    worstPain: '10 - أسوأ ألم',
    next: 'التالي',
    backToSymptoms: 'العودة إلى الأعراض',
    oneMoreQuestion: 'سؤال واحد آخر',
    preparingQuestion: 'جارٍ تحضير سؤال لك...',
    hearAgain: 'استمع مرة أخرى',
    listenToQuestion: 'استمع إلى السؤال...',
    tapToAnswer: 'اضغط على الميكروفون للإجابة',
    yourAnswer: 'إجابتك',
    answerPlaceholder: 'ستظهر إجابتك هنا...',
    typeAnswer: 'اكتب إجابتك هنا...',
    quickTitle: 'بعض الأسئلة السريعة',
    quickSub: 'هذا يساعدنا على تحديد أولوية رعايتك. يمكنك تخطي أي سؤال.',
    allergyQ: 'هل لديك حساسية من أي أدوية؟',
    whichOne: 'ما هو؟',
    allergyExample: 'مثل البنسلين',
    medsQ: 'هل تتناول أي أدوية؟',
    medsExample: 'مثل الأسبرين، الأنسولين',
    onsetQ: 'متى بدأ ذلك؟',
    detected: 'بحسب ما قلته:',
    onset: {
      'Just now': 'الآن',
      Today: 'اليوم',
      'A few days': 'منذ بضعة أيام',
      'A week or more': 'أسبوع أو أكثر',
    },
    pregnantQ: 'هل يمكن أن تكوني حاملاً؟',
    yes: 'نعم',
    no: 'لا',
    notSure: 'غير متأكد',
    analyzing: 'جارٍ تسجيلك...',
    checkIn: 'تسجيل',
    checkedIn: 'تم تسجيلك',
    inQueue: 'أنت في قائمة الانتظار. يتم فحص الحالات الأشد أولاً، لذلك قد يتغير وقت انتظارك.',
    yourTicket: 'رقم تذكرتك',
    boardNote: 'راقب شاشة غرفة الانتظار لرؤية رقمك.',
    scanQr: 'امسح الرمز لمتابعة دورك على هاتفك',
    summary: 'تسجيلك',
    symptomsLabel: 'الأعراض',
    vitalsLabel: 'المؤشرات الحيوية',
    nurseVitals: 'ستقوم ممرضة بقياس مؤشراتك الحيوية',
    pulse: 'النبض',
    feelWorse: 'إذا شعرت بسوء شديد، أخبر الموظفين فوراً.',
    done: 'تم',
    tapDone: 'اضغط على "تم" بعد مسح الرمز ليتمكن الشخص التالي من التسجيل.',
    staffNotified: 'تم إبلاغ الموظفين. سيأتي أحدهم لمساعدتك.',
    dismiss: 'إغلاق',
    intakeError: 'حدث خطأ ما. يرجى التوجه إلى مكتب الفرز.',
    networkError: 'مشكلة في الاتصال. يرجى التوجه إلى مكتب الفرز.',
  },
  pa: {
    title: 'ਐਮਰਜੈਂਸੀ ਚੈੱਕ-ਇਨ',
    subtitle: 'ਆਪਣੇ ਲੱਛਣ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦੱਸੋ।',
    selectLang: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    whoTitle: 'ਇਹ ਚੈੱਕ-ਇਨ ਕਿਸ ਲਈ ਹੈ?',
    me: 'ਮੈਂ (ਬਾਲਗ)',
    meDesc: 'ਖੁਦ ਚੈੱਕ-ਇਨ',
    child: 'ਬੱਚਾ',
    childDesc: '12 ਸਾਲ ਤੋਂ ਘੱਟ',
    someoneElse: 'ਮੇਰੇ ਨਾਲ ਕੋਈ',
    someoneElseDesc: 'ਪਰਿਵਾਰ ਦਾ ਮੈਂਬਰ ਜਾਂ ਦੋਸਤ',
    howOld: 'ਤੁਹਾਡੇ ਬੱਚੇ ਦੀ ਉਮਰ ਕਿੰਨੀ ਹੈ?',
    paediatricNote: 'ਨੋਟ: 12 ਸਾਲ ਤੋਂ ਘੱਟ ਉਮਰ ਦੇ ਬੱਚਿਆਂ ਲਈ ਕੈਮਰਾ ਸਕੈਨ ਨਹੀਂ ਹੁੰਦਾ।',
    aboutYouTitle: 'ਤੁਹਾਡੇ ਬਾਰੇ',
    stepOf: 'ਕਦਮ {n} / {total}',
    ageLabel: 'ਤੁਹਾਡੀ ਉਮਰ ਕਿੰਨੀ ਹੈ?',
    sexLabel: 'ਜਨਮ ਸਮੇਂ ਨਿਰਧਾਰਤ ਲਿੰਗ',
    female: 'ਔਰਤ',
    male: 'ਮਰਦ',
    intersex: 'ਇੰਟਰਸੈਕਸ',
    preferNot: 'ਦੱਸਣਾ ਨਹੀਂ ਚਾਹੁੰਦੇ',
    pronounsTitle: 'ਪੜਨਾਂਵ (ਮਨਚਾਹਾ)',
    nameTitle: 'ਤੁਹਾਡਾ ਨਾਮ',
    nameSubtitle: 'ਪਹਿਲਾ ਨਾਮ ਅਤੇ ਆਖਰੀ ਅੱਖਰ',
    emergencyNotice: 'ਛਾਤੀ ਵਿੱਚ ਦਰਦ ਜਾਂ ਸਾਹ ਲੈਣ ਵਿੱਚ ਤਕਲੀਫ਼? ਐਂਬੂਲੈਂਸ ਨਾਲ ਆਏ ਹੋ? ਸਿੱਧਾ ਡੈਸਕ ਤੇ ਜਾਓ।',
    back: 'ਵਾਪਸ',
    continue: 'ਅੱਗੇ ਵਧੋ',
    skip: 'ਛੱਡੋ',
    askStaff: 'ਸਟਾਫ਼ ਤੋਂ ਪੁੱਛੋ',
    interpreterOff: 'ਮੈਨੂੰ ਸੈਨਤ ਭਾਸ਼ਾ ਦੁਭਾਸ਼ੀਏ ਦੀ ਲੋੜ ਹੈ',
    interpreterOn: '✓ ਸੈਨਤ ਭਾਸ਼ਾ ਦੁਭਾਸ਼ੀਏ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ',
    alreadyCheckedIn: 'ਪਹਿਲਾਂ ਹੀ ਚੈੱਕ-ਇਨ ਕੀਤਾ ਅਤੇ ਹੋਰ ਖਰਾਬ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ?',
    years: 'ਸਾਲ',
    months: 'ਮਹੀਨੇ',
    whyWeAsk: 'ਅਸੀਂ ਕਿਉਂ ਪੁੱਛਦੇ ਹਾਂ: ਜਨਮ ਸਮੇਂ ਦਾ ਲਿੰਗ ਕੁਝ ਜੋਖਮਾਂ ਅਤੇ ਲੈਬ ਟੈਸਟਾਂ ਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
    skipPronouns: 'ਛੱਡੋ',
    pronouns: {
      'he/him': 'ਉਹ (ਪੁਰਸ਼)',
      'she/her': 'ਉਹ (ਇਸਤਰੀ)',
      'they/them': 'ਉਹ (ਨਿਰਪੱਖ)',
      other: 'ਹੋਰ',
    },
    recheckKicker: 'ਦੁਬਾਰਾ ਜਾਂਚ',
    recheckTitle: 'ਪਹਿਲਾਂ ਹੀ ਚੈੱਕ-ਇਨ ਕੀਤਾ?',
    recheckBody: 'ਆਪਣਾ ਟਿਕਟ ਨੰਬਰ ਦਰਜ ਕਰੋ (ਜਿਵੇਂ A-17) ਤਾਂ ਜੋ ਦੁਬਾਰਾ ਜਾਂਚ ਹੋ ਸਕੇ ਅਤੇ ਨਵੇਂ ਲੱਛਣ ਦੱਸ ਸਕੋ।',
    rescan: 'ਦੁਬਾਰਾ ਜਾਂਚ ਕਰੋ',
    measuring: 'ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...',
    lookAtCamera: 'ਕਿਰਪਾ ਕਰਕੇ ਕੈਮਰੇ ਵੱਲ ਦੇਖੋ ਅਤੇ ਆਮ ਵਾਂਗ ਸਾਹ ਲਓ।',
    noVideo: 'ਕੋਈ ਵੀਡੀਓ ਰਿਕਾਰਡ ਨਹੀਂ ਹੁੰਦੀ। ਸਿਰਫ਼ ਨਬਜ਼ ਅਤੇ ਸਾਹ ਮਾਪੇ ਜਾਂਦੇ ਹਨ।',
    yourPulse: 'ਤੁਹਾਡੀ ਨਬਜ਼',
    breathing: 'ਸਾਹ',
    breathsPerMin: 'ਸਾਹ/ਮਿੰਟ',
    describeTitle: 'ਆਪਣੇ ਲੱਛਣ ਦੱਸੋ',
    describeSub: 'ਹੇਠਾਂ ਦਿੱਤਾ ਬਟਨ ਦਬਾਓ ਅਤੇ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਮ ਵਾਂਗ ਬੋਲੋ।',
    tapToSpeak: 'ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
    listening: 'ਸੁਣ ਰਹੇ ਹਾਂ... ਹੁਣ ਬੋਲੋ (ਰੋਕਣ ਲਈ ਦਬਾਓ)',
    whatYouSaid: 'ਤੁਸੀਂ ਕੀ ਕਿਹਾ',
    typeInstead: 'ਲਿਖ ਕੇ ਦੱਸੋ',
    hideTextBox: 'ਲਿਖਣ ਵਾਲਾ ਡੱਬਾ ਲੁਕਾਓ',
    listeningPlaceholder: 'ਤੁਹਾਡੀ ਆਵਾਜ਼ ਸੁਣ ਰਹੇ ਹਾਂ...',
    spokenPlaceholder: 'ਤੁਹਾਡੇ ਸ਼ਬਦ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ...',
    typeSymptoms: 'ਆਪਣੇ ਲੱਛਣ ਇੱਥੇ ਲਿਖੋ...',
    painQuestion: 'ਦਰਦ ਕਿੰਨਾ ਜ਼ਿਆਦਾ ਹੈ?',
    noPain: '0 - ਕੋਈ ਦਰਦ ਨਹੀਂ',
    worstPain: '10 - ਸਭ ਤੋਂ ਜ਼ਿਆਦਾ ਦਰਦ',
    next: 'ਅੱਗੇ',
    backToSymptoms: 'ਲੱਛਣਾਂ ਤੇ ਵਾਪਸ',
    oneMoreQuestion: 'ਇੱਕ ਹੋਰ ਸਵਾਲ',
    preparingQuestion: 'ਤੁਹਾਡੇ ਲਈ ਸਵਾਲ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ...',
    hearAgain: 'ਦੁਬਾਰਾ ਸੁਣੋ',
    listenToQuestion: 'ਸਵਾਲ ਸੁਣੋ...',
    tapToAnswer: 'ਜਵਾਬ ਦੇਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
    yourAnswer: 'ਤੁਹਾਡਾ ਜਵਾਬ',
    answerPlaceholder: 'ਤੁਹਾਡਾ ਜਵਾਬ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗਾ...',
    typeAnswer: 'ਆਪਣਾ ਜਵਾਬ ਇੱਥੇ ਲਿਖੋ...',
    quickTitle: 'ਕੁਝ ਛੋਟੇ ਸਵਾਲ',
    quickSub: 'ਇਹ ਤੁਹਾਡੀ ਦੇਖਭਾਲ ਨੂੰ ਤਰਜੀਹ ਦੇਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ। ਤੁਸੀਂ ਕੋਈ ਵੀ ਸਵਾਲ ਛੱਡ ਸਕਦੇ ਹੋ।',
    allergyQ: 'ਕੀ ਤੁਹਾਨੂੰ ਕਿਸੇ ਦਵਾਈ ਤੋਂ ਐਲਰਜੀ ਹੈ?',
    whichOne: 'ਕਿਹੜੀ?',
    allergyExample: 'ਜਿਵੇਂ ਪੈਨਸਿਲਿਨ',
    medsQ: 'ਕੀ ਤੁਸੀਂ ਕੋਈ ਦਵਾਈ ਲੈਂਦੇ ਹੋ?',
    medsExample: 'ਜਿਵੇਂ ਐਸਪਰੀਨ, ਇਨਸੁਲਿਨ',
    onsetQ: 'ਇਹ ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਇਆ?',
    detected: 'ਤੁਹਾਡੀ ਗੱਲ ਮੁਤਾਬਕ:',
    onset: {
      'Just now': 'ਹੁਣੇ',
      Today: 'ਅੱਜ',
      'A few days': 'ਕੁਝ ਦਿਨ ਪਹਿਲਾਂ',
      'A week or more': 'ਇੱਕ ਹਫ਼ਤਾ ਜਾਂ ਵੱਧ',
    },
    pregnantQ: 'ਕੀ ਤੁਸੀਂ ਗਰਭਵਤੀ ਹੋ ਸਕਦੇ ਹੋ?',
    yes: 'ਹਾਂ',
    no: 'ਨਹੀਂ',
    notSure: 'ਪੱਕਾ ਨਹੀਂ ਪਤਾ',
    analyzing: 'ਚੈੱਕ-ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
    checkIn: 'ਚੈੱਕ-ਇਨ ਕਰੋ',
    checkedIn: 'ਤੁਸੀਂ ਚੈੱਕ-ਇਨ ਹੋ ਗਏ ਹੋ',
    inQueue: 'ਤੁਸੀਂ ਕਤਾਰ ਵਿੱਚ ਹੋ। ਸਭ ਤੋਂ ਬਿਮਾਰ ਮਰੀਜ਼ਾਂ ਨੂੰ ਪਹਿਲਾਂ ਦੇਖਿਆ ਜਾਂਦਾ ਹੈ, ਇਸ ਲਈ ਤੁਹਾਡਾ ਇੰਤਜ਼ਾਰ ਬਦਲ ਸਕਦਾ ਹੈ।',
    yourTicket: 'ਤੁਹਾਡਾ ਟਿਕਟ ਨੰਬਰ',
    boardNote: 'ਆਪਣੇ ਨੰਬਰ ਲਈ ਉਡੀਕ ਕਮਰੇ ਦੀ ਸਕਰੀਨ ਦੇਖੋ।',
    scanQr: 'ਆਪਣੇ ਫ਼ੋਨ ਤੇ ਆਪਣੀ ਥਾਂ ਦੇਖਣ ਲਈ ਸਕੈਨ ਕਰੋ',
    summary: 'ਤੁਹਾਡਾ ਚੈੱਕ-ਇਨ',
    symptomsLabel: 'ਲੱਛਣ',
    vitalsLabel: 'ਜਾਂਚ',
    nurseVitals: 'ਨਰਸ ਤੁਹਾਡੀ ਜਾਂਚ ਕਰੇਗੀ',
    pulse: 'ਨਬਜ਼',
    feelWorse: 'ਜੇ ਤੁਸੀਂ ਬਹੁਤ ਜ਼ਿਆਦਾ ਖਰਾਬ ਮਹਿਸੂਸ ਕਰੋ, ਤਾਂ ਤੁਰੰਤ ਸਟਾਫ਼ ਨੂੰ ਦੱਸੋ।',
    done: 'ਹੋ ਗਿਆ',
    tapDone: 'ਕੋਡ ਸਕੈਨ ਕਰਨ ਤੋਂ ਬਾਅਦ "ਹੋ ਗਿਆ" ਦਬਾਓ ਤਾਂ ਜੋ ਅਗਲਾ ਵਿਅਕਤੀ ਚੈੱਕ-ਇਨ ਕਰ ਸਕੇ।',
    staffNotified: 'ਸਟਾਫ਼ ਨੂੰ ਦੱਸ ਦਿੱਤਾ ਗਿਆ ਹੈ। ਕੋਈ ਤੁਹਾਡੀ ਮਦਦ ਲਈ ਆ ਰਿਹਾ ਹੈ।',
    dismiss: 'ਬੰਦ ਕਰੋ',
    intakeError: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਟ੍ਰਾਈਏਜ ਡੈਸਕ ਤੇ ਜਾਓ।',
    networkError: 'ਕਨੈਕਸ਼ਨ ਦੀ ਸਮੱਸਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਟ੍ਰਾਈਏਜ ਡੈਸਕ ਤੇ ਜਾਓ।',
  },
  zh: {
    title: '急诊登记',
    subtitle: '扫描体征。用您的母语描述症状。',
    selectLang: '选择语言',
    whoTitle: '本次登记对象是谁？',
    me: '本人 (成人)',
    meDesc: '自行登记',
    child: '儿童',
    childDesc: '12 岁以下',
    someoneElse: '同行人员',
    someoneElseDesc: '家属或朋友',
    howOld: '您的孩子多大？',
    paediatricNote: '儿科说明：12岁以下儿童跳过摄像头扫描。',
    aboutYouTitle: '关于您',
    stepOf: '第 {n} 步，共 {total} 步',
    ageLabel: '您的年龄是多少？',
    sexLabel: '出生生理性别 (供医疗参考)',
    female: '女',
    male: '男',
    intersex: '双性',
    preferNot: '保密',
    pronounsTitle: '代词 (选填)',
    nameTitle: '您的姓名',
    nameSubtitle: '名字及姓氏首字母',
    emergencyNotice: '胸痛或呼吸困难？乘坐救护车到达？请直接前往服务台。',
    back: '返回',
    continue: '继续',
    skip: '跳过',
    askStaff: '寻求工作人员帮助',
    interpreterOff: '我需要手语翻译',
    interpreterOn: '✓ 已申请手语翻译',
    alreadyCheckedIn: '已经登记但感觉更糟？',
    years: '岁',
    months: '个月',
    whyWeAsk: '为什么问这个：出生时的生理性别有助于评估某些风险和化验参考值。',
    skipPronouns: '跳过',
    pronouns: {
      'he/him': '他',
      'she/her': '她',
      'they/them': 'TA',
      other: '其他',
    },
    recheckKicker: '重新检查',
    recheckTitle: '已经登记过？',
    recheckBody: '输入您的号码（例如 A-17），重新测量体征并报告新的症状。',
    rescan: '重新检查',
    measuring: '正在测量体征...',
    lookAtCamera: '请看着摄像头，正常呼吸。',
    noVideo: '不会录制视频，只测量脉搏和呼吸。',
    yourPulse: '您的脉搏',
    breathing: '呼吸',
    breathsPerMin: '次/分钟',
    describeTitle: '描述您的症状',
    describeSub: '按下面的按钮，用您的语言自然地说话。',
    tapToSpeak: '点击麦克风开始说话',
    listening: '正在听...请说话（点击停止）',
    whatYouSaid: '您说的内容',
    typeInstead: '改为打字',
    hideTextBox: '隐藏文本框',
    listeningPlaceholder: '正在听您的声音...',
    spokenPlaceholder: '您说的话会显示在这里...',
    typeSymptoms: '在这里输入您的症状...',
    painQuestion: '疼痛有多严重？',
    noPain: '0 - 不痛',
    worstPain: '10 - 最痛',
    next: '下一步',
    backToSymptoms: '返回症状',
    oneMoreQuestion: '再问一个问题',
    preparingQuestion: '正在为您准备问题...',
    hearAgain: '再听一遍',
    listenToQuestion: '请听问题...',
    tapToAnswer: '点击麦克风回答',
    yourAnswer: '您的回答',
    answerPlaceholder: '您的回答会显示在这里...',
    typeAnswer: '在这里输入您的回答...',
    quickTitle: '几个简单问题',
    quickSub: '这有助于我们安排您的就诊优先级。任何问题都可以跳过。',
    allergyQ: '您对任何药物过敏吗？',
    whichOne: '哪一种？',
    allergyExample: '例如青霉素',
    medsQ: '您在服用任何药物吗？',
    medsExample: '例如阿司匹林、胰岛素',
    onsetQ: '什么时候开始的？',
    detected: '根据您说的：',
    onset: {
      'Just now': '刚刚',
      Today: '今天',
      'A few days': '几天前',
      'A week or more': '一周或更久',
    },
    pregnantQ: '您有可能怀孕吗？',
    yes: '是',
    no: '否',
    notSure: '不确定',
    analyzing: '正在为您登记...',
    checkIn: '登记',
    checkedIn: '您已登记',
    inQueue: '您已排队。病情最重的患者优先就诊，所以您的等待时间可能会变化。',
    yourTicket: '您的号码',
    boardNote: '请留意候诊室屏幕上的号码。',
    scanQr: '扫码在手机上查看您的排队位置',
    summary: '您的登记信息',
    symptomsLabel: '症状',
    vitalsLabel: '体征',
    nurseVitals: '护士会为您测量体征',
    pulse: '脉搏',
    feelWorse: '如果您感觉明显加重，请立即告诉工作人员。',
    done: '完成',
    tapDone: '扫码后请点击"完成"，以便下一位登记。',
    staffNotified: '已通知工作人员，马上有人来帮助您。',
    dismiss: '关闭',
    intakeError: '出了点问题，请前往分诊台。',
    networkError: '网络连接问题，请前往分诊台。',
  },
  ru: {
    title: 'Экстренная Регистрация',
    subtitle: 'Опишите ваши симптомы на вашем языке.',
    selectLang: 'Выберите язык',
    whoTitle: 'Для кого эта регистрация?',
    me: 'Я (Взрослый)',
    meDesc: 'Саморегистрация',
    child: 'Ребенок',
    childDesc: 'До 12 лет',
    someoneElse: 'Кто-то со мной',
    someoneElseDesc: 'Член семьи или друг',
    howOld: 'Сколько лет вашему ребенку?',
    paediatricNote: 'Детская заметка: Сканирование камерой пропускается для детей до 12 лет.',
    aboutYouTitle: 'О вас',
    stepOf: 'Шаг {n} из {total}',
    ageLabel: 'Сколько вам лет?',
    sexLabel: 'Пол при рождении',
    female: 'Женский',
    male: 'Мужской',
    intersex: 'Интерсекс',
    preferNot: 'Предпочитаю не говорить',
    pronounsTitle: 'Местоимения (необязательно)',
    nameTitle: 'Ваше имя',
    nameSubtitle: 'Имя и первая буква фамилии',
    emergencyNotice: 'Боль в груди или одышка? Приехали на скорой? Идите прямо к стойке.',
    back: 'Назад',
    continue: 'Продолжить',
    skip: 'Пропустить',
    askStaff: 'Спросить персонал',
    interpreterOff: 'Мне нужен переводчик жестового языка',
    interpreterOn: '✓ Переводчик жестового языка запрошен',
    alreadyCheckedIn: 'Уже зарегистрированы, но стало хуже?',
    years: 'лет',
    months: 'месяцев',
    whyWeAsk: 'Зачем мы спрашиваем: пол при рождении помогает оценить некоторые риски и нормы анализов.',
    skipPronouns: 'Пропустить',
    pronouns: {
      'he/him': 'он',
      'she/her': 'она',
      'they/them': 'они',
      other: 'другое',
    },
    recheckKicker: 'Повторная проверка',
    recheckTitle: 'Уже зарегистрированы?',
    recheckBody: 'Введите номер талона (например A-17), чтобы заново измерить показатели и сообщить о новых симптомах.',
    rescan: 'Повторить проверку',
    measuring: 'Измеряем показатели...',
    lookAtCamera: 'Смотрите в камеру и дышите спокойно.',
    noVideo: 'Видео не записывается. Измеряются только пульс и дыхание.',
    yourPulse: 'Ваш пульс',
    breathing: 'Дыхание',
    breathsPerMin: 'вдох/мин',
    describeTitle: 'Опишите ваши симптомы',
    describeSub: 'Нажмите кнопку ниже и говорите на своём языке.',
    tapToSpeak: 'Нажмите на микрофон, чтобы говорить',
    listening: 'Слушаем... говорите (нажмите, чтобы остановить)',
    whatYouSaid: 'Что вы сказали',
    typeInstead: 'Написать текстом',
    hideTextBox: 'Скрыть поле ввода',
    listeningPlaceholder: 'Слушаем ваш голос...',
    spokenPlaceholder: 'Здесь появятся ваши слова...',
    typeSymptoms: 'Опишите симптомы здесь...',
    painQuestion: 'Насколько сильная боль?',
    noPain: '0 - Нет боли',
    worstPain: '10 - Сильнейшая боль',
    next: 'Далее',
    backToSymptoms: 'Назад к симптомам',
    oneMoreQuestion: 'Ещё один вопрос',
    preparingQuestion: 'Готовим для вас вопрос...',
    hearAgain: 'Прослушать ещё раз',
    listenToQuestion: 'Послушайте вопрос...',
    tapToAnswer: 'Нажмите на микрофон, чтобы ответить',
    yourAnswer: 'Ваш ответ',
    answerPlaceholder: 'Здесь появится ваш ответ...',
    typeAnswer: 'Напишите ответ здесь...',
    quickTitle: 'Несколько быстрых вопросов',
    quickSub: 'Это помогает определить срочность помощи. Любой вопрос можно пропустить.',
    allergyQ: 'Есть ли у вас аллергия на лекарства?',
    whichOne: 'На какое?',
    allergyExample: 'например, пенициллин',
    medsQ: 'Вы принимаете какие-либо лекарства?',
    medsExample: 'например, аспирин, инсулин',
    onsetQ: 'Когда это началось?',
    detected: 'Судя по вашим словам:',
    onset: {
      'Just now': 'Только что',
      Today: 'Сегодня',
      'A few days': 'Несколько дней назад',
      'A week or more': 'Неделю или больше',
    },
    pregnantQ: 'Возможна ли у вас беременность?',
    yes: 'Да',
    no: 'Нет',
    notSure: 'Не уверен(а)',
    analyzing: 'Регистрируем вас...',
    checkIn: 'Зарегистрироваться',
    checkedIn: 'Вы зарегистрированы',
    inQueue: 'Вы в очереди. Самых тяжёлых пациентов принимают первыми, поэтому время ожидания может измениться.',
    yourTicket: 'Ваш номер талона',
    boardNote: 'Следите за своим номером на экране в зале ожидания.',
    scanQr: 'Отсканируйте, чтобы следить за очередью на телефоне',
    summary: 'Ваша регистрация',
    symptomsLabel: 'Симптомы',
    vitalsLabel: 'Показатели',
    nurseVitals: 'Медсестра измерит ваши показатели',
    pulse: 'Пульс',
    feelWorse: 'Если вам станет намного хуже, сразу сообщите персоналу.',
    done: 'Готово',
    tapDone: 'Нажмите «Готово» после сканирования кода, чтобы следующий человек мог зарегистрироваться.',
    staffNotified: 'Персонал уведомлён. Вам скоро помогут.',
    dismiss: 'Закрыть',
    intakeError: 'Что-то пошло не так. Пожалуйста, подойдите к стойке сортировки.',
    networkError: 'Проблема со связью. Пожалуйста, подойдите к стойке сортировки.',
  },
};

export const kioskStrings = (code) => KIOSK_STRINGS[code] || KIOSK_STRINGS.en;
