export const PHONE_STRINGS = {
  en: {
    title: "You're checked in",
    ahead: 'people ahead of you',
    live: 'Updates automatically. You can leave this page and come back anytime.',
    ticket: 'Your ticket',
    feelingWorse: 'Feeling worse? Tap here',
    calledTitle: 'You are being called',
    calledBody: 'Please come to room 3',
    recheckTitle: 'Re-check requested',
    recheckBody: 'The nurse would like to check on you again.',
    kioskSteps: 'For a new vitals scan, go to the kiosk, tap "Already checked in and feeling worse?" and enter your ticket number.',
    updateTitle: 'What has changed?',
    updatePlaceholder: 'Describe how you feel now',
    painNow: 'Pain right now',
    send: 'Send to nurse',
    sent: 'Sent. The nurse can see your update.',
    messageFrom: 'Message from the nurse',
    loading: 'Loading your place in line...',
    notFoundTitle: 'Check-in not found',
    notFoundBody: 'Please speak to the triage desk.',
    scanQrHint: 'Scan the QR code on your check-in screen to follow your place in line.',
    networkError: 'Connection problem. Trying again...',
    dismiss: 'Dismiss',
    messages: {
      come_to_desk: 'Please come to the desk.',
      nurse_soon: 'A nurse will call you soon.',
    },
  },
  fr: {
    title: 'Vous êtes enregistré',
    ahead: 'personnes avant vous',
    live: 'Mise à jour automatique. Vous pouvez quitter cette page et revenir à tout moment.',
    ticket: 'Votre ticket',
    feelingWorse: 'Vous vous sentez plus mal ? Appuyez ici',
    calledTitle: 'On vous appelle',
    calledBody: 'Veuillez vous rendre à la salle 3',
    recheckTitle: 'Nouvelle vérification demandée',
    recheckBody: "L'infirmière souhaite vous réévaluer.",
    kioskSteps: 'Pour un nouveau scan, allez à la borne, appuyez sur « Déjà enregistré ? » et entrez votre numéro de ticket.',
    updateTitle: "Qu'est-ce qui a changé ?",
    updatePlaceholder: 'Décrivez comment vous vous sentez',
    painNow: 'Douleur actuelle',
    send: "Envoyer à l'infirmière",
    sent: "Envoyé. L'infirmière voit votre message.",
    messageFrom: "Message de l'infirmière",
    loading: 'Chargement de votre place dans la file...',
    notFoundTitle: 'Enregistrement introuvable',
    notFoundBody: 'Veuillez vous adresser à l\'accueil.',
    scanQrHint: 'Scannez le code QR affiché à la fin de votre enregistrement pour suivre votre place.',
    networkError: 'Problème de connexion. Nouvelle tentative...',
    dismiss: 'Fermer',
    messages: {
      come_to_desk: 'Veuillez vous présenter au comptoir.',
      nurse_soon: 'Une infirmière va vous appeler bientôt.',
    },
  },
  es: {
    title: '¡Registro completado!',
    ahead: 'personas delante de usted',
    live: 'Se actualiza solo. Puede salir de esta página y volver cuando quiera.',
    ticket: 'Su número',
    feelingWorse: '¿Se siente peor? Toque aquí',
    calledTitle: 'Le están llamando',
    calledBody: 'Por favor, pase a la sala 3',
    recheckTitle: 'Nueva revisión solicitada',
    recheckBody: 'La enfermera quiere revisarle de nuevo.',
    kioskSteps: 'Para un nuevo escaneo, vaya al quiosco, toque "¿Ya se registró?" e ingrese su número.',
    updateTitle: '¿Qué ha cambiado?',
    updatePlaceholder: 'Describa cómo se siente ahora',
    painNow: 'Dolor ahora',
    send: 'Enviar a la enfermera',
    sent: 'Enviado. La enfermera puede ver su mensaje.',
    messageFrom: 'Mensaje de la enfermera',
    loading: 'Cargando su lugar en la fila...',
    notFoundTitle: 'Registro no encontrado',
    notFoundBody: 'Por favor, hable con el mostrador de triaje.',
    scanQrHint: 'Escanee el código QR de su registro para seguir su lugar en la fila.',
    networkError: 'Problema de conexión. Reintentando...',
    dismiss: 'Cerrar',
    messages: {
      come_to_desk: 'Por favor, acérquese al mostrador.',
      nurse_soon: 'Una enfermera le llamará pronto.',
    },
  },
  ar: {
    title: 'تم تسجيلك بنجاح',
    ahead: 'أشخاص قبلك في الانتظار',
    live: 'يتم التحديث تلقائياً. يمكنك مغادرة الصفحة والعودة في أي وقت.',
    ticket: 'رقم تذكرتك',
    feelingWorse: 'هل تشعر بسوء؟ اضغط هنا',
    calledTitle: 'يتم استدعاؤك الآن',
    calledBody: 'يرجى التوجه إلى الغرفة ٣',
    recheckTitle: 'مطلوب فحص جديد',
    recheckBody: 'تود الممرضة فحصك مرة أخرى.',
    kioskSteps: 'لفحص جديد، توجه إلى الجهاز، واضغط على "مسجل بالفعل؟" وأدخل رقم تذكرتك.',
    updateTitle: 'ما الذي تغير؟',
    updatePlaceholder: 'صف شعورك الآن',
    painNow: 'الألم الآن',
    send: 'إرسال إلى الممرضة',
    sent: 'تم الإرسال. يمكن للممرضة رؤية رسالتك.',
    messageFrom: 'رسالة من الممرضة',
    loading: 'جارٍ تحميل دورك في قائمة الانتظار...',
    notFoundTitle: 'لم يتم العثور على التسجيل',
    notFoundBody: 'يرجى التحدث إلى مكتب الفرز.',
    scanQrHint: 'امسح رمز QR الظاهر عند التسجيل لمتابعة دورك.',
    networkError: 'مشكلة في الاتصال. جارٍ إعادة المحاولة...',
    dismiss: 'إغلاق',
    messages: {
      come_to_desk: 'يرجى الحضور إلى المكتب.',
      nurse_soon: 'ستناديك الممرضة قريباً.',
    },
  },
  pa: {
    title: 'ਤੁਸੀਂ ਚੈੱਕ-ਇਨ ਹੋ ਗਏ ਹੋ',
    ahead: 'ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਲੋਕ',
    live: 'ਆਪਣੇ ਆਪ ਅੱਪਡੇਟ ਹੁੰਦਾ ਹੈ। ਤੁਸੀਂ ਕਦੇ ਵੀ ਇਸ ਪੰਨੇ ਤੇ ਵਾਪਸ ਆ ਸਕਦੇ ਹੋ।',
    ticket: 'ਤੁਹਾਡੀ ਟਿਕਟ',
    feelingWorse: 'ਹੋਰ ਖਰਾਬ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ? ਇੱਥੇ ਟੈਪ ਕਰੋ',
    calledTitle: 'ਤੁਹਾਨੂੰ ਬੁਲਾਇਆ ਜਾ ਰਿਹਾ ਹੈ',
    calledBody: 'ਕਿਰਪਾ ਕਰਕੇ ਕਮਰਾ 3 ਵਿੱਚ ਆਓ',
    recheckTitle: 'ਦੁਬਾਰਾ ਜਾਂਚ ਦੀ ਬੇਨਤੀ',
    recheckBody: 'ਨਰਸ ਤੁਹਾਡੀ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰਨਾ ਚਾਹੁੰਦੀ ਹੈ।',
    kioskSteps: 'ਨਵੇਂ ਸਕੈਨ ਲਈ, ਕਿਓਸਕ ਤੇ ਜਾਓ, "ਪਹਿਲਾਂ ਹੀ ਚੈੱਕ-ਇਨ?" ਦਬਾਓ ਅਤੇ ਆਪਣਾ ਟਿਕਟ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
    updateTitle: 'ਕੀ ਬਦਲਿਆ ਹੈ?',
    updatePlaceholder: 'ਦੱਸੋ ਤੁਸੀਂ ਹੁਣ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ',
    painNow: 'ਹੁਣ ਦਰਦ',
    send: 'ਨਰਸ ਨੂੰ ਭੇਜੋ',
    sent: 'ਭੇਜਿਆ ਗਿਆ। ਨਰਸ ਤੁਹਾਡਾ ਅੱਪਡੇਟ ਦੇਖ ਸਕਦੀ ਹੈ।',
    messageFrom: 'ਨਰਸ ਵੱਲੋਂ ਸੁਨੇਹਾ',
    loading: 'ਕਤਾਰ ਵਿੱਚ ਤੁਹਾਡੀ ਥਾਂ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
    notFoundTitle: 'ਚੈੱਕ-ਇਨ ਨਹੀਂ ਮਿਲਿਆ',
    notFoundBody: 'ਕਿਰਪਾ ਕਰਕੇ ਟ੍ਰਾਈਏਜ ਡੈਸਕ ਤੇ ਗੱਲ ਕਰੋ।',
    scanQrHint: 'ਆਪਣੀ ਥਾਂ ਦੇਖਣ ਲਈ ਚੈੱਕ-ਇਨ ਸਕਰੀਨ ਵਾਲਾ QR ਕੋਡ ਸਕੈਨ ਕਰੋ।',
    networkError: 'ਕਨੈਕਸ਼ਨ ਦੀ ਸਮੱਸਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਹੋ ਰਹੀ ਹੈ...',
    dismiss: 'ਬੰਦ ਕਰੋ',
    messages: {
      come_to_desk: 'ਕਿਰਪਾ ਕਰਕੇ ਡੈਸਕ ਤੇ ਆਓ।',
      nurse_soon: 'ਨਰਸ ਜਲਦੀ ਹੀ ਤੁਹਾਨੂੰ ਬੁਲਾਏਗੀ।',
    },
  },
  zh: {
    title: '您已成功登记',
    ahead: '人排在您前面',
    live: '自动更新。您可以随时离开并返回此页面。',
    ticket: '您的号码',
    feelingWorse: '感到病情加重？点击此处',
    calledTitle: '正在叫您的号',
    calledBody: '请到3号诊室',
    recheckTitle: '需要重新检查',
    recheckBody: '护士希望再次为您检查。',
    kioskSteps: '如需重新测量，请到自助机点击"已经登记？"并输入您的号码。',
    updateTitle: '有什么变化？',
    updatePlaceholder: '请描述您现在的感受',
    painNow: '当前疼痛程度',
    send: '发送给护士',
    sent: '已发送，护士可以看到您的更新。',
    messageFrom: '护士留言',
    loading: '正在加载您的排队位置...',
    notFoundTitle: '未找到登记信息',
    notFoundBody: '请到分诊台咨询。',
    scanQrHint: '请扫描登记时显示的二维码查看排队位置。',
    networkError: '网络连接问题，正在重试...',
    dismiss: '关闭',
    messages: {
      come_to_desk: '请到服务台来。',
      nurse_soon: '护士很快会叫您。',
    },
  },
  ru: {
    title: 'Вы зарегистрированы',
    ahead: 'человек перед вами',
    live: 'Обновляется автоматически. Можно уйти со страницы и вернуться в любое время.',
    ticket: 'Ваш талон',
    feelingWorse: 'Стало хуже? Нажмите здесь',
    calledTitle: 'Вас вызывают',
    calledBody: 'Пожалуйста, пройдите в кабинет 3',
    recheckTitle: 'Требуется повторный осмотр',
    recheckBody: 'Медсестра хочет осмотреть вас ещё раз.',
    kioskSteps: 'Для нового сканирования подойдите к терминалу, нажмите «Уже зарегистрированы?» и введите номер талона.',
    updateTitle: 'Что изменилось?',
    updatePlaceholder: 'Опишите, как вы себя чувствуете',
    painNow: 'Боль сейчас',
    send: 'Отправить медсестре',
    sent: 'Отправлено. Медсестра видит ваше сообщение.',
    messageFrom: 'Сообщение от медсестры',
    loading: 'Загружаем ваше место в очереди...',
    notFoundTitle: 'Регистрация не найдена',
    notFoundBody: 'Пожалуйста, обратитесь к стойке сортировки.',
    scanQrHint: 'Отсканируйте QR-код с экрана регистрации, чтобы следить за очередью.',
    networkError: 'Проблема со связью. Пробуем снова...',
    dismiss: 'Закрыть',
    messages: {
      come_to_desk: 'Пожалуйста, подойдите к стойке.',
      nurse_soon: 'Медсестра скоро вас вызовет.',
    },
  },
};

export const phoneStrings = (languageCode) => PHONE_STRINGS[languageCode] || PHONE_STRINGS.en;
