export const PHONE_STRINGS = {
  en: {
    title: "You're checked in",
    position: 'Current position',
    ahead: 'people ahead of you',
    live: 'Updates automatically. You can leave this page and come back anytime.',
    ticket: 'Your ticket',
    feelingWorse: 'Feeling worse? Tap here',
    calledTitle: 'You are being called',
    calledBody: 'Please come to room 3',
    recheckTitle: 'Re-check requested',
    recheckBody: 'The nurse would like to check on you again.',
    kioskSteps: 'For a new vitals scan, go to the kiosk, tap "Already checked in and feeling worse?" and enter your ticket number.',
    updateTitle: 'What has changed?',
    updatePlaceholder: 'Describe how you feel now',
    painNow: 'Pain right now',
    send: 'Send to nurse',
    sent: 'Sent. The nurse can see your update.',
    alertsOff: 'Tap to turn on sound alerts',
    alertsOn: 'Sound alerts on',
    messageFrom: 'Message from the nurse',
    messages: {
      come_to_desk: 'Please come to the desk.',
      nurse_soon: 'A nurse will call you soon.',
    },
  },
  fr: {
    title: 'Vous êtes enregistré',
    position: 'Votre position',
    ahead: 'personnes avant vous',
    live: 'Mise à jour automatique. Vous pouvez quitter cette page et revenir à tout moment.',
    ticket: 'Votre ticket',
    feelingWorse: 'Vous vous sentez plus mal ? Appuyez ici',
    calledTitle: 'On vous appelle',
    calledBody: 'Veuillez vous rendre à la salle 3',
    recheckTitle: 'Nouvelle vérification demandée',
    recheckBody: "L'infirmière souhaite vous réévaluer.",
    kioskSteps: 'Pour un nouveau scan, allez à la borne, appuyez sur « Déjà enregistré ? » et entrez votre numéro de ticket.',
    updateTitle: "Qu'est-ce qui a changé ?",
    updatePlaceholder: 'Décrivez comment vous vous sentez',
    painNow: 'Douleur actuelle',
    send: "Envoyer à l'infirmière",
    sent: "Envoyé. L'infirmière voit votre message.",
    alertsOff: 'Appuyez pour activer les alertes sonores',
    alertsOn: 'Alertes sonores activées',
    messageFrom: "Message de l'infirmière",
    messages: {
      come_to_desk: 'Veuillez vous présenter au comptoir.',
      nurse_soon: 'Une infirmière va vous appeler bientôt.',
    },
  },
  es: {
    title: '¡Registro completado!',
    position: 'Su posición',
    ahead: 'personas delante de usted',
    live: 'Se actualiza solo. Puede salir de esta página y volver cuando quiera.',
    ticket: 'Su número',
    feelingWorse: '¿Se siente peor? Toque aquí',
    calledTitle: 'Le están llamando',
    calledBody: 'Por favor, pase a la sala 3',
    recheckTitle: 'Nueva revisión solicitada',
    recheckBody: 'La enfermera quiere revisarle de nuevo.',
    kioskSteps: 'Para un nuevo escaneo, vaya al quiosco, toque "¿Ya se registró?" e ingrese su número.',
    updateTitle: '¿Qué ha cambiado?',
    updatePlaceholder: 'Describa cómo se siente ahora',
    painNow: 'Dolor ahora',
    send: 'Enviar a la enfermera',
    sent: 'Enviado. La enfermera puede ver su mensaje.',
    alertsOff: 'Toque para activar las alertas de sonido',
    alertsOn: 'Alertas de sonido activadas',
    messageFrom: 'Mensaje de la enfermera',
    messages: {
      come_to_desk: 'Por favor, acérquese al mostrador.',
      nurse_soon: 'Una enfermera le llamará pronto.',
    },
  },
  ar: {
    title: 'تم تسجيلك بنجاح',
    position: 'ترتيبك الحالي',
    ahead: 'أشخاص قبلك في الانتظار',
    live: 'يتم التحديث تلقائياً. يمكنك مغادرة الصفحة والعودة في أي وقت.',
    ticket: 'رقم تذكرتك',
    feelingWorse: 'هل تشعر بسوء؟ اضغط هنا',
    calledTitle: 'يتم استدعاؤك الآن',
    calledBody: 'يرجى التوجه إلى الغرفة ٣',
    recheckTitle: 'مطلوب فحص جديد',
    recheckBody: 'تود الممرضة فحصك مرة أخرى.',
    kioskSteps: 'لفحص جديد، توجه إلى الجهاز، واضغط على "مسجل بالفعل؟" وأدخل رقم تذكرتك.',
    updateTitle: 'ما الذي تغير؟',
    updatePlaceholder: 'صف شعورك الآن',
    painNow: 'الألم الآن',
    send: 'إرسال إلى الممرضة',
    sent: 'تم الإرسال. يمكن للممرضة رؤية رسالتك.',
    alertsOff: 'اضغط لتفعيل التنبيهات الصوتية',
    alertsOn: 'التنبيهات الصوتية مفعلة',
    messageFrom: 'رسالة من الممرضة',
    messages: {
      come_to_desk: 'يرجى الحضور إلى المكتب.',
      nurse_soon: 'ستناديك الممرضة قريباً.',
    },
  },
  pa: {
    title: 'ਤੁਸੀਂ ਚੈੱਕ-ਇਨ ਹੋ ਗਏ ਹੋ',
    position: 'ਤੁਹਾਡੀ ਥਾਂ',
    ahead: 'ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਲੋਕ',
    live: 'ਆਪਣੇ ਆਪ ਅੱਪਡੇਟ ਹੁੰਦਾ ਹੈ। ਤੁਸੀਂ ਕਦੇ ਵੀ ਇਸ ਪੰਨੇ ਤੇ ਵਾਪਸ ਆ ਸਕਦੇ ਹੋ।',
    ticket: 'ਤੁਹਾਡੀ ਟਿਕਟ',
    feelingWorse: 'ਹੋਰ ਖਰਾਬ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ? ਇੱਥੇ ਟੈਪ ਕਰੋ',
    calledTitle: 'ਤੁਹਾਨੂੰ ਬੁਲਾਇਆ ਜਾ ਰਿਹਾ ਹੈ',
    calledBody: 'ਕਿਰਪਾ ਕਰਕੇ ਕਮਰਾ 3 ਵਿੱਚ ਆਓ',
    recheckTitle: 'ਦੁਬਾਰਾ ਜਾਂਚ ਦੀ ਬੇਨਤੀ',
    recheckBody: 'ਨਰਸ ਤੁਹਾਡੀ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰਨਾ ਚਾਹੁੰਦੀ ਹੈ।',
    kioskSteps: 'ਨਵੇਂ ਸਕੈਨ ਲਈ, ਕਿਓਸਕ ਤੇ ਜਾਓ, "ਪਹਿਲਾਂ ਹੀ ਚੈੱਕ-ਇਨ?" ਦਬਾਓ ਅਤੇ ਆਪਣਾ ਟਿਕਟ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
    updateTitle: 'ਕੀ ਬਦਲਿਆ ਹੈ?',
    updatePlaceholder: 'ਦੱਸੋ ਤੁਸੀਂ ਹੁਣ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ',
    painNow: 'ਹੁਣ ਦਰਦ',
    send: 'ਨਰਸ ਨੂੰ ਭੇਜੋ',
    sent: 'ਭੇਜਿਆ ਗਿਆ। ਨਰਸ ਤੁਹਾਡਾ ਅੱਪਡੇਟ ਦੇਖ ਸਕਦੀ ਹੈ।',
    alertsOff: 'ਆਵਾਜ਼ ਵਾਲੀਆਂ ਸੂਚਨਾਵਾਂ ਚਾਲੂ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ',
    alertsOn: 'ਆਵਾਜ਼ ਵਾਲੀਆਂ ਸੂਚਨਾਵਾਂ ਚਾਲੂ ਹਨ',
    messageFrom: 'ਨਰਸ ਵੱਲੋਂ ਸੁਨੇਹਾ',
    messages: {
      come_to_desk: 'ਕਿਰਪਾ ਕਰਕੇ ਡੈਸਕ ਤੇ ਆਓ।',
      nurse_soon: 'ਨਰਸ ਜਲਦੀ ਹੀ ਤੁਹਾਨੂੰ ਬੁਲਾਏਗੀ।',
    },
  },
  zh: {
    title: '您已成功登记',
    position: '当前位置',
    ahead: '人排在您前面',
    live: '自动更新。您可以随时离开并返回此页面。',
    ticket: '您的号码',
    feelingWorse: '感到病情加重？点击此处',
    calledTitle: '正在叫您的号',
    calledBody: '请到3号诊室',
    recheckTitle: '需要重新检查',
    recheckBody: '护士希望再次为您检查。',
    kioskSteps: '如需重新测量，请到自助机点击"已经登记？"并输入您的号码。',
    updateTitle: '有什么变化？',
    updatePlaceholder: '请描述您现在的感受',
    painNow: '当前疼痛程度',
    send: '发送给护士',
    sent: '已发送，护士可以看到您的更新。',
    alertsOff: '点击开启声音提醒',
    alertsOn: '声音提醒已开启',
    messageFrom: '护士留言',
    messages: {
      come_to_desk: '请到服务台来。',
      nurse_soon: '护士很快会叫您。',
    },
  },
  ru: {
    title: 'Вы зарегистрированы',
    position: 'Ваше место в очереди',
    ahead: 'человек перед вами',
    live: 'Обновляется автоматически. Можно уйти со страницы и вернуться в любое время.',
    ticket: 'Ваш талон',
    feelingWorse: 'Стало хуже? Нажмите здесь',
    calledTitle: 'Вас вызывают',
    calledBody: 'Пожалуйста, пройдите в кабинет 3',
    recheckTitle: 'Требуется повторный осмотр',
    recheckBody: 'Медсестра хочет осмотреть вас ещё раз.',
    kioskSteps: 'Для нового сканирования подойдите к терминалу, нажмите «Уже зарегистрированы?» и введите номер талона.',
    updateTitle: 'Что изменилось?',
    updatePlaceholder: 'Опишите, как вы себя чувствуете',
    painNow: 'Боль сейчас',
    send: 'Отправить медсестре',
    sent: 'Отправлено. Медсестра видит ваше сообщение.',
    alertsOff: 'Нажмите, чтобы включить звуковые оповещения',
    alertsOn: 'Звуковые оповещения включены',
    messageFrom: 'Сообщение от медсестры',
    messages: {
      come_to_desk: 'Пожалуйста, подойдите к стойке.',
      nurse_soon: 'Медсестра скоро вас вызовет.',
    },
  },
};

export const phoneStrings = (languageCode) => PHONE_STRINGS[languageCode] || PHONE_STRINGS.en;
